import { createContext } from "react";

import Head from "next/head";

import { Home } from "./Home";
import { HomeProps } from "@/shared/types/HomeProps";

export const HomeContext = createContext<HomeProps>({
  allBalance: 0,
  allStatements: [],
  accounts: [],
});

export async function getServerSideProps() {
  // Get All Balance
  const getAllBalance = await fetch("http://localhost:3333/balance/all");
  const allBalance = await getAllBalance.json();

  // Get All Accounts
  const getAccounts = await fetch("http://localhost:3333/accounts");
  const accounts = await getAccounts.json();

  // Get All Statements
  const getAllStatements = await fetch("http://localhost:3333/statement/all");
  const allStatements = await getAllStatements.json();

  // Pass data to the page via props
  return { props: { allBalance, accounts, allStatements } };
}

export default function Index({
  allBalance,
  accounts,
  allStatements,
}: HomeProps) {
  return (
    <>
      <Head>
        <title>FinanceApp.js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <HomeContext.Provider value={{ allBalance, allStatements, accounts }}>
          <Home />
        </HomeContext.Provider>
      </main>
    </>
  );
}
