import { createContext } from "react";

import Head from "next/head";

import { Home } from "./home";
import { HomeProps } from "@/shared/types/HomeProps";

export const HomeContext = createContext<HomeProps>({
  allBalance: 0,
  allExpenses: 0,
  allStatements: [],
  accounts: [],
});

export async function getServerSideProps() {
  const reqAllBalance = await fetch("http://localhost:3333/balance/all");
  const allBalance = await reqAllBalance.json();

  const reqAllExpenses = await fetch("http://localhost:3333/expenses/all");
  const allExpenses = await reqAllExpenses.json();

  const reqAccounts = await fetch("http://localhost:3333/accounts");
  const accounts = await reqAccounts.json();

  const getAllStatements = await fetch("http://localhost:3333/statement/all");
  const allStatements = await getAllStatements.json();

  return { props: { allBalance, accounts, allStatements, allExpenses } };
}

export default function Index({
  allBalance,
  accounts,
  allStatements,
  allExpenses,
}: HomeProps) {
  return (
    <>
      <Head>
        <title>FinanceApp.js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <HomeContext.Provider
          value={{ allBalance, allStatements, accounts, allExpenses }}
        >
          <Home />
        </HomeContext.Provider>
      </main>
    </>
  );
}
